### ISSUE TITLE
Raiden Shogun doesn't charge attack | Sprint also not working?

### ISSUE THREAD

**Issue by mmaine** [phonowell/genshin-impact-script#76]
This could be me just misusing the actions, but:

`on-long-press = a~`

doesn't seem to cause raiden to charge attack, but chain autos. 

Also, it seems using sprint with `s` doesn't seem to work either. Couldn't find anything in issues, so posting here in case.

edit; `a~` doesn't also seem to work on Tartaglia during his melee stance.

**Comment by phonowell** [comment]
This issue was fixed in v28.
Have a go :)

**Comment by thu2468** [comment]
sprint still not working. im testing it with hu tao. i did this to test
[hu_tao]
on-long-press = s

**Comment by phonowell** [comment]
well there was a typo mistake
and it will be fixed in v29 asap
